apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app-set
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: my-app-set
  targetNamespace: default
  syncPolicy:
    automated: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: my-app-set
    spec:
      source:
        path: environment-values/{{.Values.valuesFile}}
        repository: https://github.com/ojp2/prev-test.git
      project: default
      targetRevision: HEAD
      destination:
  server: https://kubernetes.default.svc
  namespace: prev-test
  syncOptions:
    - Validate=true
    - CreateNamespace=true
  apps:
  - name: app1
    values:
      valuesFile: app1-values.yaml
  - name: app2
    values:
      valuesFile: app2-values.yaml
  - ...
